/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jasmine (https://sketchfab.com/jasmineemilycornell)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/japanese-tori-gate-11c75832cc91469cb98eccdfc28c6eeb
title: Japanese Tori Gate
*/

import React, { useEffect, useLayoutEffect, useRef, useState } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import { useSpring } from "@react-spring/core";
import { a } from "@react-spring/three";

export default function Model({ ...props }) {
  const [active, setActive] = useState(0);
  const group = useRef();
  const { nodes, materials } = useGLTF("/torigate.gltf");
  const { spring } = useSpring({
    spring: active,
    config: { mass: 5, tension: 400, friction: 50, precision: 0.0001 },
  });
  const rotation = spring.to([0, 1], [0, Math.PI*2]);
  useLayoutEffect(() =>
    Object.values(nodes).forEach(
      (node) => (node.receiveShadow = node.castShadow = true)
    )
  );

  useEffect(() => {
    setActive(Number(!active));
  }, []);

  return (
    <a.group ref={group} {...props} dispose={null}>
      <a.group rotation={[-Math.PI / 2, 0, 0]}>
        <a.group rotation={[Math.PI / 2, 0, 0]}>
          <a.mesh
            rotation-y={rotation}
            geometry={nodes.pCube3_lambert1_0.geometry}
            material={materials.lambert1}
          />
        </a.group>
      </a.group>
    </a.group>
  );
}

useGLTF.preload("/torigate.gltf");
